### ISSUE TITLE
Cleaning up subscriptions?

### ISSUE THREAD

**Issue by mtraynham** [scaljeri/angular-xxl#1]
Cool library, seems very useful.  I was looking at the code a bit to see what it does and was wondering if there's currently an issue with subscriptions dangling and not being garbage collected, most notable here, https://github.com/scaljeri/angular-xxl/blob/master/src/route.decorators.ts#L91.

I think it's common practice to use [ngOnDestroy](https://angular.io/guide/lifecycle-hooks#ondestroy) to remove any subscriptions that you created throughout the component lifecycle so there are no memory leaks.

**Comment by scaljeri** [comment]
Good point, I will investigate this, to see if this is indeed needed! Thnx

**Comment by scaljeri** [comment]
It turns out that it is not needed: https://stackblitz.com/edit/angular-route-xxl-bf3aki?file=app%2Futils%2Froute-decorator.ts

See also: https://stackoverflow.com/questions/41138081/do-i-have-to-unsubscribe-from-activatedroute-e-g-params-observables
